### ISSUE TITLE
Bug fixing and improvements to the code

### ISSUE THREAD

**Issue by julianduque** [YanKlInnomme/FoundryVTT-kult-divinity-lost#1]
Hello @YanKlInnomme!

I'm currently working on improvements to the system, fixing some bugs I found, and migrating this to Foundry v10. I'll propose a pull request this weekend (either today or tomorrow) with all those enhancements. Thanks for keeping a backup of this and I'm planning on continuing contributing if that is ok with you.

Best,

**Comment by YanKlInnomme** [comment]
How can I put it? I have already done a complete overhaul of the system with :

    Code cleanup and migration to V10 by Christophe Laudon (https://github.com/Qaw)
    Global redesign of the Injury management process done by Christophe Laudon (https://github.com/Qaw)
    Addition of the field 'Options' in Actions to avoid the display 'undefined' in the chat

The code is available at the following address:
[https://github.com/YanKlInnomme/FoundryVTT-k4lt](https://github.com/YanKlInnomme/FoundryVTT-k4lt)

![Capture d’écran 2023-02-24 122622](https://user-images.githubusercontent.com/100078854/221369778-9f5dca7d-4bac-40e6-afb1-45bac7cb0b98.jpg)
![Capture d’écran 2023-02-24 122605](https://user-images.githubusercontent.com/100078854/221369801-f74c3164-a84a-4be3-997b-ef087c098ff3.jpg)

**Comment by julianduque** [comment]
Wow, that's way better! I thought the system was abandoned but you have done a fantastic job. I have never worked on a Foundry system/module before so it was a good learning experience. I'll take a look at the other fork and maybe in the future contribute there. Nothing to do here then ;)
